'use strict';
const DETAILS_GET_REQUEST = 'DETAILS_GET_REQUEST';
const DETAILS_GET_FAILURE = 'DETAILS_GET_FAILURE';
const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';

export {DETAILS_GET_REQUEST, DETAILS_GET_FAILURE, DETAILS_GET_SUCCESS };