const ITEMS_GET_REQUEST = 'ITEMS_GET_REQUEST';
const ITEMS_GET_FAILURE = 'ITEMS_GET_FAILURE';
const ITEMS_GET_SUCCESS = 'ITEMS_GET_SUCCESS';
const DELETE_ITEM = 'DELETE_ITEM';

export {ITEMS_GET_REQUEST, ITEMS_GET_FAILURE, ITEMS_GET_SUCCESS, DELETE_ITEM};